import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { KeychainCredentialStore } from "./credentials/keychain.js";
import { EtsyClient } from "./etsy/client.js";
import { ListingService } from "./etsy/listings.js";
import { OrderService } from "./etsy/orders.js";
import { GoogleClient } from "./google/client.js";
import { GoogleDriveService } from "./google/drive.js";
import { DriveImportService } from "./import/drive-import.js";
import { LocalConfigStore } from "./local-config.js";
import { createServer } from "./server.js";
import { GoogleFolderToolService } from "./tools/google-tools.js";
import { DraftWriteService } from "./tools/write-tools.js";
import { ConfirmationStore } from "./writes/confirmations.js";

const store = new KeychainCredentialStore();
const client = new EtsyClient({ store });
const listings = new ListingService(client, store);
const orders = new OrderService(client, store);
const writes = new DraftWriteService(client, listings, store, new ConfirmationStore());
const localConfig = new LocalConfigStore();
const googleClient = new GoogleClient(store);
const googleDrive = new GoogleDriveService(googleClient, localConfig);
const googleFolders = new GoogleFolderToolService(googleDrive);
const driveImports = new DriveImportService(googleDrive);
const server = createServer({ store, listings, orders, writes, googleFolders, driveImports });
await server.connect(new StdioServerTransport());
