import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { FileAmazonAdsChangeLog } from "./amazon/ads-change-log.js";
import { AmazonAdsClient } from "./amazon/ads-client.js";
import { AmazonSpApiClient } from "./amazon/sp-api-client.js";
import { KeychainCredentialStore } from "./credentials/keychain.js";
import { EtsyClient } from "./etsy/client.js";
import { ListingService } from "./etsy/listings.js";
import { OrderService } from "./etsy/orders.js";
import { GoogleClient } from "./google/client.js";
import { GoogleDriveService } from "./google/drive.js";
import { GoogleOAuth } from "./google/oauth.js";
import { GoogleDriveHealthService } from "./google/status.js";
import { DriveImageUploadService } from "./import/drive-image-upload.js";
import { DriveImportService } from "./import/drive-import.js";
import { LocalConfigStore } from "./local-config.js";
import { createServer } from "./server.js";
import { AmazonAdsWriteService, AmazonListingWriteService } from "./tools/amazon-tools.js";
import { GoogleFolderToolService } from "./tools/google-tools.js";
import { DraftWriteService } from "./tools/write-tools.js";
import { ConfirmationStore } from "./writes/confirmations.js";

const store = new KeychainCredentialStore();
const client = new EtsyClient({ store });
const listings = new ListingService(client, store);
const orders = new OrderService(client, store);
const writes = new DraftWriteService(client, listings, store, new ConfirmationStore());
const localConfig = new LocalConfigStore();
const googleClient = new GoogleClient(store);
const googleDrive = new GoogleDriveService(googleClient, localConfig);
const googleFolders = new GoogleFolderToolService(googleDrive);
const googleHealth = new GoogleDriveHealthService(store, localConfig, new GoogleOAuth(store));
const driveImports = new DriveImportService(googleDrive, googleHealth);
const driveImageUploads = new DriveImageUploadService(client, listings, googleDrive, store, new ConfirmationStore(), googleHealth);
const amazonAds = new AmazonAdsClient(store);
const amazonSpApi = new AmazonSpApiClient(store);
const amazonListingWrites = new AmazonListingWriteService(store, amazonSpApi, new ConfirmationStore());
const amazonAdsChangeLog = new FileAmazonAdsChangeLog();
const amazonAdsWrites = new AmazonAdsWriteService(amazonAds, new ConfirmationStore(), amazonAdsChangeLog);
const server = createServer({ store, listings, orders, writes, googleFolders, googleHealth, driveImports, driveImageUploads, amazonAds, amazonSpApi, amazonListingWrites, amazonAdsWrites, amazonAdsChangeLog });
await server.connect(new StdioServerTransport());
